// Generated by https://quicktype.io

class Author {
  List<Value> value;
  List<Link> links;

  Author({
    this.value,
    this.links,
  });

  factory Author.fromJson(Map<String, dynamic> json) {
    return Author(
      value: json['value'],
      links: json['links'],
    );
  }
}

class Link {
  String href;
  Rel rel;
  Method method;

  Link({
    this.href,
    this.rel,
    this.method,
  });

  factory Link.fromJson(Map<String, dynamic> json) {
    return Link(
      href: json['href'],
      rel: json['rel'],
      method: json['method'] as Method
    );
  }
}

enum Method { GET, DELETE, POST }

enum Rel { SELF, COURSES, CREATE_COURSE_FOR_AUTHOR }

class Value {
  String id;
  String name;
  int age;
  String mainCategory;
  List<Link> links;

  Value({
    this.id,
    this.name,
    this.age,
    this.mainCategory,
    this.links,
  });

  factory Value.fromJson(Map<String, dynamic> json) {
    return Value(
      id: json['id'],
      name: json['name'],
      age: json['age'],
      mainCategory: json['category'],
      links: json['links']
    );
  }
}
